name: extensions_package
description: Collection of extensions used in app and package development
version: 0.2.1+6
homepage: http://www.raehealth.com
publish_to: 'none'

environment:
  sdk: ">=2.16.0 <3.0.0" #Dart SDK 2022-02-04
  flutter: ">=2.10.0"

dependencies:
  cupertino_icons: ^1.0.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  flutter_modular: ^4.4.0

dependency_overrides: null

dev_dependencies:
  build_runner:
  test:

flutter:
  uses-material-design: true
  generate: false
