name: extensions_package
description: Collection of extensions used in app and package development
version: 0.2.0+5
homepage: http://www.raehealth.com
publish_to: 'none'

environment:
  sdk: ">=2.15.1 <3.0.0" #Dart SDK 2021-12-20
  flutter: ">=2.8.1"

dependencies:
  cupertino_icons: ^1.0.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  flutter_modular: ^4.3.0

dependency_overrides: null

dev_dependencies:
  build_runner:
  test:

flutter:
  uses-material-design: true
  generate: false
