name: extensions_package
description: Collection of extensions used in app and package development
version: 0.0.1+12
homepage: http://www.raehealth.com
publish_to: 'none'

environment:
  sdk: ">=2.15.1 <3.0.0" #Dart SDK 2021-12-20
  flutter: ">=2.8.1"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4
  flutter_bloc: ^8.0.0
  flutter_localizations:
    sdk: flutter
  flutter_modular: ^4.2.0
  intl: ^0.17.0

dev_dependencies:
  test: ^1.20.1

flutter:
  uses-material-design: true
  generate: true
